---
- name: remi-release is installed?
  command: rpm -q remi-release
  register: exit
  failed_when: exit.rc not in [0, 1]

- name: install remi-release
  yum:  name=http://rpms.famillecollet.com/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm state=present
  when: exit.rc == 1
